### ISSUE TITLE
Couldn't fetch catalog data from JSON

### ISSUE THREAD

**Issue by jbellanca** [PieterVeldman/FSFilmDownloader#3]
Trying to download from this catalog:
https://www.familysearch.org/ark:/61903/3:1:3QSQ-G9MZ-4CN7?i=6539&cc=1947613&cat=382540

And the extension throws this error, and won't download any images:
"Couldn't fetch catalog data from JSON"

**Comment by ACBSmith** [comment]
I've had the same issue here and not easily been able to resolve it. @jbellanca - did you find a solution to this at all?

I'm using the latest version of the extension and Chrome 105.0.5195.125 running on OSX 12.5.1

**Comment by PieterVeldman** [comment]
Sorry guys. FamilySearch asked me to discontinue the extension. They were afraid people might misuse it and infringe the deals they have with the owners of the films. I am not able to support the tool anymore.
